### ISSUE TITLE
Must/Must Not conditions should use different lang strings

### ISSUE THREAD

**Issue by danmarsden** [danielneis/moodle-availability_maxviews#3]
When the maxviews is set to "Must" the current lang string makes sense. but when it is set to "must not" the lang string does not describe the actual behaviour.

**Comment by danielneis** [comment]
Hello,

in fact, it would not make sense to use it with "must not" because with "you must not have at most 10 views" the user will never have a chance to view the module. Is there a way to disable the use of a condition for "must not" ? Or better, can you think of a good behaviour for the "must not" case?

Kind regards,
Daniel

**Comment by danmarsden** [comment]
I could see the restriction being used when a new version of an activity is added 

For example user 1 completes activity 1 which is required before viewing the course certificate.
Teacher uploads new version of activity 1 but wants previously completed users to still see their previous completion/activity but does not want that old activity to show to users that have not made any attempts.
